name: Remote Server Deployer

on:
  push:
    branches: 
    - staging
  pull_request:
    branches:
    - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ssh deploy
        # You may pin to the exact commit or the version.
        # uses: easingthemes/ssh-deploy@8be4106fcece54a488146d4db78e270310feb10f
        uses: easingthemes/ssh-deploy@v4.0.0
        with:
          # Private key part of an SSH key pair
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # Remote host
          REMOTE_HOST: ${{ secrets.HOST }}
          # Remote user
          REMOTE_USER: ${{secrets.USERNAME }}
          # Remote port
          # Source directory, path relative to `$GITHUB_WORKSPACE` root, eg: `dist/`
          SOURCE: .
          # Target directory
          TARGET: /home/adelwort/Desktop/deep-net-prod
          # Script to run on host machine after rsync
          SCRIPT_AFTER: echo "second test!" >> /home/adelwort/Desktop/output_here.txt
          
