name: Remote Server Deployer

on:
  push:
    branches: 
    - staging
  pull_request:
    branches:
    - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: SSH Server Deploy
        # You may pin to the exact commit or the version.
        # uses: kostyaten/ssh-server-deploy@e0deb814bc458a68b61f6597a865d096e33eb586
        uses: kostyaten/ssh-server-deploy@v4
        with:
          # Host
          host: ssh.cs.brown.edu
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          after_script: |
            echo "the after_script command worked" >> /home/adelwort/Desktop/deep-net-prod/test_echo.txt
          scp_target: /home/adelwort/Desktop/deep-net-prod
          
