name: Remote Server Deployer

on:
  push:
    branches: 
    - staging
  pull_request:
    branches:
    - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ssh deploy
        # You may pin to the exact commit or the version.
        # uses: easingthemes/ssh-deploy@8be4106fcece54a488146d4db78e270310feb10f
        uses: easingthemes/ssh-deploy@v4.0.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SOURCE: .
          TARGET: /home/adelwort/Desktop/deep-net-prod
          SCRIPT_AFTER: echo "second test2!" >> /home/adelwort/Desktop/output_here.txt
          
