name: Remote Server Deployer

on:
  push:
    branches: 
    - staging
  pull_request:
    branches:
    - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create dir
        run:
          mkdir -p ~/.ssh
      - name: Add Hosts
        run:
          ssh-keyscan -H ssh.cs.brown.edu >> ~/.ssh/known_hosts
      - name: Install SSH Key
        # You may pin to the exact commit or the version.
        # uses: shimataro/ssh-key-action@02d189fc92ea6279c0fea0e7a259da1b4f1d22a5
        uses: shimataro/ssh-key-action@v2.5.0
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Check ssh
        run:
          ssh -v adelwort@ssh.cs.brown.edu && echo "Hello andy2" >> /home/adelwort/Desktop/nf.txt
      - name: ssh deploy
        # You may pin to the exact commit or the version.
        # uses: easingthemes/ssh-deploy@8be4106fcece54a488146d4db78e270310feb10f
        uses: easingthemes/ssh-deploy@v4.0.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REMOTE_HOST: ssh.cs.brown.edu
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_PORT: 22 -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa
          SOURCE: .
          TARGET: /home/adelwort/Desktop/deep-net-prod
          SCRIPT_AFTER: echo "second test222!" >> /home/adelwort/Desktop/output_here.txt
          
